name: project_dokan
description: wedevs Job Project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.4+4
  http: ^0.13.4
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  rflutter_alert: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter:
  uses-material-design: true
  assets:
    - images/
    - jasonFile/response.json

flutter_icons:
  android: "launcher_icon"
  image_path: "images/icon.png"
